apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      name: spring-boot-app
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: b20dccn728/spring-boot-app:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      